repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "5e374fd"
    hooks:
      - id: prettier
  - repo: local
    hooks:
      - id: next-lint
        name: Run Next Lint
        language: node
        entry: npm run lint:fix
        pass_filenames: false
