image:
  tag: "v2.8.3"

ports:
  websecure:
    tls:
      enabled: true
      certResolver: leresolver
  web:
    expose: true
    # redirectTo: websecure

deployment:
  initContainers:
    - name: volume-permissions
      image: busybox:1.31.1
      command: ["sh", "-c", "chmod -Rv 600 /data/*"]
      volumeMounts:
        - name: data
          mountPath: /data

persistence:
  # persists the /data directory
  name: data
  enabled: true
  size: 128Mi

logs:
  general:
    level: DEBUG

certResolvers:
  leresolver:
    email: me@alexjball.com
    httpchallenge:
      entrypoint: "web"
    tlschallenge: true
    storage: /data/acme.json
    # Please note that this is the staging Let's Encrypt server.
    # Once you get things working, you should remove that whole line altogether.
    caserver: "https://acme-staging-v02.api.letsencrypt.org/directory"

additionalArguments:
  - --providers.providersthrottleduration=100
