apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: typesense-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: "{{ .Values.storageClassName }}"
