apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ..

helmCharts:
  - name: app
    # include the traefik CRD's
    includeCRDs: true
    releaseName: dev
    valuesInline:
      apiDomain: maple.aballslab.com
      storageClassName: local-path
      secretName: typesense

resources:
  - ./typesense-secrets.yml
