apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ..

helmCharts:
  - name: app
    # include the traefik CRD's
    includeCRDs: true
    releaseName: prod
    valuesInline:
      apiDomain: maple-prod.alexjball.com
      storageClassName: standard-rwo
      secretName: typesense

resources:
  - ./typesense-secrets.yml

patches:
  # Set the IP of traefik to match the reserved, static regional IP
  # https://cloud.google.com/kubernetes-engine/docs/tutorials/configuring-domain-name-static-ip#use_a_service
  - patch: |-
      - op: add
        path: /spec/loadBalancerIP
        value: 35.224.191.63
    target:
      version: v1
      kind: Service
      name: prod-traefik
