name: Build Pull Request

on: [pull_request]

jobs:
  build:
    # Don't build forks, even if actions are enabled
    if: github.repository_owner == 'codeforboston'
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Build Environment
        uses: ./.github/actions/setup-repo
      - name: Build App
        run: yarn export:nolint
      - name: Export App
        uses: actions/upload-artifact@v2
        if: github.event_name == 'pull_request'
        with:
          name: digital-testimony-app
          path: out
          retention-days: 1
